### ISSUE TITLE
Introdurre la possibilità di commentare singole porzioni di testo

### ISSUE THREAD

**Issue by giuragu** [giuragu/regolamento-bilancio-democrazia-partecipata-sangiuseppejato#2]
Sarebbe utile introdurre la possibilità di commentare singole porzioni di testo.
Come fare?
- Strumento natio su Read The Docs?
- Disqus
- Altro?

**Comment by gbvitrano** [comment]
se ci sono pagine dove i commenti non sono necessari o li vuoi disattivare, ti basta inserire in alto questo codice nel file .md in oggetto


```
---
disqus: ""
---
```
