### ISSUE TITLE
Progetto Mkdocs-Material di riferimento

### ISSUE THREAD

**Issue by gbvitrano** [giuragu/regolamento-bilancio-democrazia-partecipata-sangiuseppejato#6]
Sarebbe meglio se nel file [note.md](https://github.com/giuragu/regolamento-bilancio-democrazia-partecipata-sangiuseppejato/blob/master/note.md) si sostituisse il progetto di rifermento, [https://gbvitrano.github.io/MaterialMkDocs-gb/](https://gbvitrano.github.io/MaterialMkDocs-gb/) è un pò complesso per chi si approccia a Material MkDocs, c'è troppa roba da ripulire. 

Potreste mettere [https://opendatasicilia.github.io/ods-mkdocs-material](https://opendatasicilia.github.io/ods-mkdocs-material/) = [https://github.com/opendatasicilia/ods-mkdocs-material/blob/main/mkdocs.yml](https://github.com/opendatasicilia/ods-mkdocs-material/blob/main/mkdocs.yml) già pronto all'uso  per github anche per le gh-pages, evitando di utilizzare [https://readthedocs.org/](https://readthedocs.org/) per il rendering html

Ps. sempre [ods-mkdocs-material](https://github.com/opendatasicilia/ods-mkdocs-material) ho aggiunto nel [mkdocs.yml](https://github.com/opendatasicilia/ods-mkdocs-material/blob/main/mkdocs.yml) le istruzioni per l'installazione di **Disqus**

**Comment by giuragu** [comment]
Credo di aver fatto quanto chiedi @gbvitrano. puoi verificare?

**Comment by gbvitrano** [comment]
> Credo di aver fatto quanto chiedi @gbvitrano. puoi verificare?

Si, Grazie :-)
chiudo issue
